import { Ropa_Sans } from 'next/font/google';  // Import Ropa Sans font
import localFont from 'next/font/local';
import './globals.css';

// Local Fonts
const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

// Google Font: Ropa Sans
const ropaSans = Ropa_Sans({
  weight: '400', // Specify the font weight you want (you can adjust as needed)
  subsets: ['latin'], // Choose the character sets you need
  variable: '--font-ropa-sans', // Custom CSS variable for easy application
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined"
          rel="stylesheet"
        />
        </head>
      <body
      
        className={`${geistSans.variable} ${geistMono.variable} ${ropaSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
